/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.hightail.ui;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.Map.Entry;
import javax.swing.AbstractAction;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import org.hightail.KeyboardShortcuts;

/**
 *
 * @author krig
 */
public class ShortcutsJDialog extends javax.swing.JDialog {

    /**
     * Creates new form ShortcutsJDialog
     */
    public ShortcutsJDialog(java.awt.Frame parent) {
        super(parent, true); // makes it modal
        initComponents();
        
        setLocationRelativeTo(parent);
        
        makeShortcuts();
        
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        shortcutsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Shortcuts");

        shortcutsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Action", "Shorcut"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        shortcutsTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(shortcutsTable);
        shortcutsTable.getColumnModel().getColumn(0).setResizable(false);
        shortcutsTable.getColumnModel().getColumn(1).setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void makeShortcuts() {
        // escape key will close the dialog
        getRootPane().getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "close");
        getRootPane().getActionMap().put("close", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });
    }
    
    private void fillTable() {
        DefaultTableModel model = (DefaultTableModel) shortcutsTable.getModel();
        for (Entry<String,String> shortcut : new KeyboardShortcuts()) {
            model.addRow(new String[]{shortcut.getKey(), shortcut.getValue()});
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable shortcutsTable;
    // End of variables declaration//GEN-END:variables
}
